################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c \
../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c \
../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c \
../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c \
../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.c 

OBJS += \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.o \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.o \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.o \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.o \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.o 

C_DEPS += \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.d \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.d \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.d \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.d \
./Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.o: ../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.c Middlewares/STM32_USB_Device_Library/Class/MSC/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.o: ../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.c Middlewares/STM32_USB_Device_Library/Class/MSC/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_bot.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.o: ../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.c Middlewares/STM32_USB_Device_Library/Class/MSC/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_data.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.o: ../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.c Middlewares/STM32_USB_Device_Library/Class/MSC/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_scsi.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.o: ../Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.c Middlewares/STM32_USB_Device_Library/Class/MSC/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_USB_Device_Library/Class/MSC/Src/usbd_msc_storage_template.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

