################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.c \
../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.c 

OBJS += \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.o \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.o 

C_DEPS += \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.d \
./Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/hci_tl_if.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/shci_tl_if.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_mbox.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_thread_hci.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.o: ../Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.c Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl/tl_zigbee_hci.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

