################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.c \
../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.c 

OBJS += \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.o \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.o 

C_DEPS += \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.d \
./Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.d 


# Each subdirectory must supply rules for building sources it contributes
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/common.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/config_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/generic_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/light_lc.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/sensors_client.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/time_scene.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.o: ../Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.c Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m4 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DUSE_STM32WBXX_NUCLEO -DDEBUG -DSTM32WB55xx -c -I../../Core/Inc -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Class/CDC/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_USB_Device_Library/Core/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/vcp" -I../../STM32_WPAN/App -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/STM32WBxx_HAL_Driver/Inc/Legacy" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/lpm/tiny_lpm" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/tl" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/interface/patterns/ble_thread/shci" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/utilities" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/auto" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/core/template" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Inc" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble/svc/Src" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Device/ST/STM32WBxx/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Utilities/sequencer" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Middlewares/STM32_WPAN/ble" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/CMSIS/Include" -I"Q:/DOKSI/EGYETEM/DTU/SYNTHESIS/STMProject/BLE_p2pServer/STM32CubeIDE/Drivers/BSP/P-NUCLEO-WB55.Nucleo" -O0 -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"Middlewares/STM32_WPAN/ble/mesh/MeshModel/Src/vendor.d" -MT"$@" --specs=nano.specs -mfpu=fpv4-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

